#!/bin/bash

set -e

RED='\033[0;31m'
NC='\033[0m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
BLUE='\033[0;34m'
LBLUE='\033[1;34m'
DGRAY='\033[1;35m'
PURPLE='\033[0;35m'
RGRAY='\033[1;30m'
BOLD=$(tput bold)
NORM=$(tput sgr0)
ORANGE='\033[1;33m'

CURRENTUSER=$(whoami)

BASE="/opt/Matsya"
sudo mkdir -p $BASE
sudo mkdir -p $BASE/tmp
sudo mkdir -p $BASE/Scripts
sudo mkdir -p $BASE/Secrets
sudo mkdir -p $BASE/Resources
sudo mkdir -p $BASE/Output

USERINTERACTION="YES"
USERVALS=""
NEEDTOGENERATE="NO"
NEEDTOVALGENERATE=""

DIFF=$((600000-500000+1))
R=$(($(($RANDOM%$DIFF))+500000))
RANDOMFILENAME=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 15 | head -n 1)
RANDOMKEY=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 15 | head -n 1)
RKEY1=${RANDOMKEY:0:7}
RKEY2=${RANDOMKEY:7:8}
RANDOMKEY="$RKEY1$R$RKEY2"

if [ "$#" -ne 1 ]; then
	USERVALS=""
else
	USERVALS=$1
	USERINTERACTION="NO"
	IFS='├' read -r -a USERLISTVALS <<< $USERVALS
	AUTH_DATA="${USERLISTVALS[0]}"
	THEFINALPATH="${USERLISTVALS[1]}"
	
	RANDOMKEY="${USERLISTVALS[2]}"
	if [ "$RANDOMKEY" == "GENERATEPLAIN" ] || [ "$RANDOMKEY" == "GENERATEJSON" ] ; then
		NEEDTOVALGENERATE="$RANDOMKEY"
		R=$(($(($RANDOM%$DIFF))+500000))
		RANDOMKEY=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 15 | head -n 1)
		RKEY1=${RANDOMKEY:0:7}
		RKEY2=${RANDOMKEY:7:8}
		RANDOMKEY="$RKEY1$R$RKEY2"
		NEEDTOGENERATE="YES"		
	else
		R=${RANDOMKEY:7:6}
	fi
	
	RANDOMFILENAME="${USERLISTVALS[3]}"					
fi

if [ "$USERINTERACTION" == "YES" ] || [ "$USERINTERACTION" == "yes" ] ; then
	clear

	echo -e "${ORANGE}========================================================================================${NC}"
	echo -e "\x1b[1;34mN\x1b[metwork \x1b[1;34mA\x1b[mccess \x1b[1;34mR\x1b[mestricted \x1b[1;34mA\x1b[mugmented \x1b[1;34mS\x1b[mecurity \x1b[1;34mI\x1b[mnfrastructure \x1b[1;34mM\x1b["${NC}"itigating \x1b[1;34mH\x1b[mazardous \x1b[1;34mA\x1b[mttacks"
	echo -e "${GREEN}========================================================================================${NC}"
	echo ''
	echo -e "\x1b[3mN   N  AAAAA  RRRRR  AAAAA  SSSS   III  M   M  H   H  AAAAA\x1b[m"
	echo -e "\x1b[3mNN  N  A   A  R   R  A   A  S       I   MM MM  H   H  A   A\x1b[m"
	echo -e "\x1b[3mN N N  AAAAA  RRRRR  AAAAA   SSS    I   M M M  HHHHH  AAAAA\x1b[m"
	echo -e "\x1b[3mN  NN  A   A  R  R   A   A      S   I   M   M  H   H  A   A\x1b[m"
	echo -e "\x1b[3mN   N  A   A  R   R  A   A  SSSS   III  M   M  H   H  A   A\x1b[m"
	echo ''
	echo -e "\x1b[3m\x1b[4mSecret File Encryption\x1b[m"
	echo ''
fi

if [ "$USERINTERACTION" == "YES" ] || [ "$USERINTERACTION" == "yes" ] ; then
	read -p "Normal File Path 	> " -e -i "$BASE/Secrets/" AUTH_DATA
	echo "                                                                         "
	read -p "Encrypted File Path 	> $BASE/Secrets/." -e -i "$RANDOMFILENAME" RANDOMFILENAME
	echo "                                                                         "
	read -p "Encrypted File Key 	> " -e -i "$RANDOMKEY" RANDOMKEY
	echo "                                                                         "
fi

if [ -f "$AUTH_DATA" ]
then	
	sudo cp $AUTH_DATA $BASE/Secrets/$RANDOMFILENAME
	sudo chown $CURRENTUSER:$CURRENTUSER $BASE/Secrets/$RANDOMFILENAME
	sudo chmod u=r,g=,o= $BASE/Secrets/$RANDOMFILENAME
	openssl enc -a -aes-256-cbc -pbkdf2 -iter $R -in $BASE/Secrets/$RANDOMFILENAME -out $BASE/Secrets/".$RANDOMFILENAME" -k $RANDOMKEY
	sudo chown $CURRENTUSER:$CURRENTUSER $BASE/Secrets/".$RANDOMFILENAME"
	sudo chmod u=r,g=,o= $BASE/Secrets/".$RANDOMFILENAME"
	sudo rm -rf $BASE/Secrets/$RANDOMFILENAME
	
	if [ "$USERINTERACTION" == "NO" ] || [ "$USERINTERACTION" == "no" ] ; then
		sudo mv $BASE/Secrets/".$RANDOMFILENAME" $THEFINALPATH
		sudo chmod u=rx,g=rx,o=rx $THEFINALPATH
	fi
	
	if [ "$USERINTERACTION" == "YES" ] || [ "$USERINTERACTION" == "yes" ] ; then
		echo -e "${PURPLE}-----------------------${NC}"
		echo -e "${PURPLE}${BOLD}PROCESS INFO${NORM}${NC}"
		echo -e "${PURPLE}-----------------------${NC}"
		echo -e "${BOLD}ORIGINAL FILE 		=> $AUTH_DATA${NORM} (${RED}\x1b[5m\x1b[3m\x1b[4mRECOMMENDED TO DELETE\x1b[m)${NC}"		
		echo -e "${BOLD}SECRET FILE   		=> $BASE/Secrets/.$RANDOMFILENAME${NORM}"
		echo -e "${BOLD}SECRET KEY    		=> $RANDOMKEY${NORM}"	
		echo -e "${PURPLE}-----------------------${NORM}"
	fi
			
	sudo rm -rf /root/.bash_history
	sudo rm -rf /home/$CURRENTUSER/.bash_history
	
	if [ "$USERINTERACTION" == "YES" ] || [ "$USERINTERACTION" == "yes" ] ; then
		echo ''
	fi
	
	if [ "$NEEDTOGENERATE" == "YES" ] ; then
		if [ "$NEEDTOVALGENERATE" == "GENERATEPLAIN" ] || [ "$NEEDTOVALGENERATE" == "generateplain" ] ; then
			echo "$RANDOMKEY"
		fi
		if [ "$NEEDTOVALGENERATE" == "GENERATEJSON" ] || [ "$NEEDTOVALGENERATE" == "generatejson" ] ; then
			echo "{\"SecretKey\": \"$RANDOMKEY\"}"
		fi			
	fi
else
	exit
fi

