#!/bin/bash

# https://console.cloud.google.com/gcr/images/cadvisor/global/cadvisor@sha256:2f3ea45c7ee3d7a0ce9f9d55a5053bd12285b02aca307ce9657af8e3ea7f6761/details?tab=vulnz
# wget https://dl.min.io/client/mc/release/linux-amd64/mc.$(curl -s https://api.github.com/repos/minio/mc/releases/latest | grep tag_name | cut -d '"' -f 4)

THECURRENTVERSIONOFSANATANIMPL="1.0"

CLUSTER_APPS_TOTAL_NUMBER="21"

declare -A CLUSTER_APPS_NUMBERING
CLUSTER_APPS_NUMBERING["1"]="BRAHMA"
CLUSTER_APPS_NUMBERING["2"]="VISHVAKARMA"
CLUSTER_APPS_NUMBERING["3"]="INDRA"
CLUSTER_APPS_NUMBERING["4"]="BUCKET"
CLUSTER_APPS_NUMBERING["5"]="CLOUDCOMMANDER"
CLUSTER_APPS_NUMBERING["6"]="PVTCLD"
CLUSTER_APPS_NUMBERING["7"]="BUCKETCLIENT"
CLUSTER_APPS_NUMBERING["8"]="CHITRAGUPTA1"
CLUSTER_APPS_NUMBERING["9"]="CHITRAGUPTA2"
CLUSTER_APPS_NUMBERING["10"]="CHITRAGUPTA3"
CLUSTER_APPS_NUMBERING["11"]="CHITRAGUPTA4"
CLUSTER_APPS_NUMBERING["12"]="CHITRAGUPTA5"
CLUSTER_APPS_NUMBERING["13"]="CHITRAGUPTA6"
CLUSTER_APPS_NUMBERING["14"]="CHITRAGUPTA7"
CLUSTER_APPS_NUMBERING["15"]="CHITRAGUPTA8"
CLUSTER_APPS_NUMBERING["16"]="CHITRAGUPTA9"
CLUSTER_APPS_NUMBERING["17"]="CHITRAGUPTA10"
CLUSTER_APPS_NUMBERING["18"]="CHITRAGUPTA11"
CLUSTER_APPS_NUMBERING["19"]="EFK1"
CLUSTER_APPS_NUMBERING["20"]="EFK2"
CLUSTER_APPS_NUMBERING["21"]="EFK3"

#CLUSTER_APPS_OTHER_DETAILS["BRAHMA"]="{\"Name\":\"GETITDYNAMICALLY1\",\"DisplayName\":\"BRAHMA\",\"CoreStack\":true,\"Configurable\":true,\"Hidden\":false,\"Memory\":\"GETITDYNAMICALLY2\",\"Cores\":GETITDYNAMICALLY3,\"Version\":\"GETITDYNAMICALLY4\",\"Suite\":\"NA\",\"SuiteVersion\":\"NA\",\"OpenSource\":true,\"IconUrl\":\"BRAHMA.png\",\"DownloadUrl\":\"GETITDYNAMICALLY5\",\"Identifier\":\"kafka_confluent_zk\",\"Properties\":[{\"Name\":\"port\",\"value\":\"2181\",\"type\":\"private\"},{\"Name\":\"dataDir\",\"value\":\"\",\"type\":\"public\"},{\"Name\":\"id\",\"value\":\"1\",\"type\":\"protected\"}],\"AppId\":7}"

declare -A CLUSTER_APPS_OTHER_DETAILS
CLUSTER_APPS_OTHER_DETAILS["BRAHMA"]='{"Name":"GETITDYNAMICALLY1","DisplayName":"BRAHMA","CoreStack":"Y","Deployable":"Y","Configurable":"Y","Hidden":"N","Memory":"GETITDYNAMICALLY2","Cores":"GETITDYNAMICALLY3","Version":"GETITDYNAMICALLY4","Suite":"NA","SuiteVersion":"NA","OpenSource":"Y","IconUrl":"GETITDYNAMICALLY7","DownloadUrl":"https://hub.docker.com/r/GETITDYNAMICALLY5/tags","Identifier":"GETITDYNAMICALLY8","Properties":[],"AppId":GETITDYNAMICALLY6}'
CLUSTER_APPS_OTHER_DETAILS["VISHVAKARMA"]='{"Name":"GETITDYNAMICALLY1","DisplayName":"VISHVAKARMA","CoreStack":"Y","Deployable":"Y","Configurable":"N","Hidden":"Y","Memory":"GETITDYNAMICALLY2","Cores":"GETITDYNAMICALLY3","Version":"GETITDYNAMICALLY4","Suite":"NA","SuiteVersion":"NA","OpenSource":"Y","IconUrl":"GETITDYNAMICALLY7","DownloadUrl":"https://hub.docker.com/r/GETITDYNAMICALLY5/tags","Identifier":"GETITDYNAMICALLY8","Properties":[],"AppId":GETITDYNAMICALLY6}'
CLUSTER_APPS_OTHER_DETAILS["INDRA"]='{"Name":"GETITDYNAMICALLY1","DisplayName":"INDRA","CoreStack":"Y","Deployable":"Y","Configurable":"Y","Hidden":"N","Memory":"GETITDYNAMICALLY2","Cores":"GETITDYNAMICALLY3","Version":"GETITDYNAMICALLY4","Suite":"NA","SuiteVersion":"NA","OpenSource":"Y","IconUrl":"GETITDYNAMICALLY7","DownloadUrl":"https://hub.docker.com/_/haproxy/tags","Identifier":"HAProxy","Properties":[],"AppId":GETITDYNAMICALLY6}'
CLUSTER_APPS_OTHER_DETAILS["BUCKET"]='{"Name":"GETITDYNAMICALLY1","DisplayName":"Minio","CoreStack":"Y","Deployable":"Y","Configurable":"Y","Hidden":"N","Memory":"GETITDYNAMICALLY2","Cores":"GETITDYNAMICALLY3","Version":"GETITDYNAMICALLY4","Suite":"NA","SuiteVersion":"NA","OpenSource":"Y","IconUrl":"GETITDYNAMICALLY7","DownloadUrl":"https://hub.docker.com/r/GETITDYNAMICALLY5/tags","Identifier":"Minio","Properties":[],"AppId":GETITDYNAMICALLY6}'
CLUSTER_APPS_OTHER_DETAILS["CLOUDCOMMANDER"]='{"Name":"GETITDYNAMICALLY1","DisplayName":"Cloud Commander","CoreStack":"Y","Deployable":"Y","Configurable":"Y","Hidden":"N","Memory":"GETITDYNAMICALLY2","Cores":"GETITDYNAMICALLY3","Version":"GETITDYNAMICALLY4","Suite":"NA","SuiteVersion":"NA","OpenSource":"Y","IconUrl":"GETITDYNAMICALLY7","DownloadUrl":"https://hub.docker.com/r/GETITDYNAMICALLY5/tags","Identifier":"CloudCommander","Properties":[],"AppId":GETITDYNAMICALLY6}'
CLUSTER_APPS_OTHER_DETAILS["PVTCLD"]='{"Name":"GETITDYNAMICALLY1","DisplayName":"Nextcloud","CoreStack":"Y","Deployable":"Y","Configurable":"Y","Hidden":"N","Memory":"GETITDYNAMICALLY2","Cores":"GETITDYNAMICALLY3","Version":"GETITDYNAMICALLY4","Suite":"NA","SuiteVersion":"NA","OpenSource":"Y","IconUrl":"GETITDYNAMICALLY7","DownloadUrl":"https://hub.docker.com/r/GETITDYNAMICALLY5/tags","Identifier":"Nextcloud","Properties":[],"AppId":GETITDYNAMICALLY6}'
CLUSTER_APPS_OTHER_DETAILS["BUCKETCLIENT"]='{"Name":"GETITDYNAMICALLY1","DisplayName":"MC","CoreStack":"Y","Deployable":"Y","Configurable":"N","Hidden":"Y","Memory":"GETITDYNAMICALLY2","Cores":"GETITDYNAMICALLY3","Version":"GETITDYNAMICALLY4","Suite":"NA","SuiteVersion":"NA","OpenSource":"Y","IconUrl":"GETITDYNAMICALLY7","DownloadUrl":"https://dl.min.io/client/mc/release/linux-amd64/","Identifier":"GETITDYNAMICALLY8","Properties":[],"AppId":GETITDYNAMICALLY6}'
CLUSTER_APPS_OTHER_DETAILS["CHITRAGUPTA1"]='{"Name":"GETITDYNAMICALLY1","DisplayName":"Apache Guacamole","CoreStack":"Y","Deployable":"Y","Configurable":"Y","Hidden":"N","Memory":"GETITDYNAMICALLY2","Cores":"GETITDYNAMICALLY3","Version":"GETITDYNAMICALLY4","Suite":"NA","SuiteVersion":"NA","OpenSource":"Y","IconUrl":"GETITDYNAMICALLY7","DownloadUrl":"https://hub.docker.com/r/GETITDYNAMICALLY5/tags","Identifier":"Guacamole","Properties":[],"AppId":GETITDYNAMICALLY6}'
CLUSTER_APPS_OTHER_DETAILS["CHITRAGUPTA2"]='{"Name":"GETITDYNAMICALLY1","DisplayName":"Apache Guacamole","CoreStack":"Y","Deployable":"Y","Configurable":"N","Hidden":"Y","Memory":"GETITDYNAMICALLY2","Cores":"GETITDYNAMICALLY3","Version":"GETITDYNAMICALLY4","Suite":"NA","SuiteVersion":"NA","OpenSource":"Y","IconUrl":"GETITDYNAMICALLY7","DownloadUrl":"https://hub.docker.com/r/GETITDYNAMICALLY5/tags","Identifier":"GuacamoleD","Properties":[],"AppId":GETITDYNAMICALLY6}'
CLUSTER_APPS_OTHER_DETAILS["CHITRAGUPTA3"]='{"Name":"GETITDYNAMICALLY1","DisplayName":"MySQL","CoreStack":"Y","Deployable":"Y","Configurable":"Y","Hidden":"N","Memory":"GETITDYNAMICALLY2","Cores":"GETITDYNAMICALLY3","Version":"GETITDYNAMICALLY4","Suite":"NA","SuiteVersion":"NA","OpenSource":"Y","IconUrl":"GETITDYNAMICALLY7","DownloadUrl":"https://hub.docker.com/r/GETITDYNAMICALLY5/tags","Identifier":"MySQL","Properties":[],"AppId":GETITDYNAMICALLY6}'
CLUSTER_APPS_OTHER_DETAILS["CHITRAGUPTA4"]='{"Name":"GETITDYNAMICALLY1","DisplayName":"phpMyAdmin","CoreStack":"Y","Deployable":"Y","Configurable":"Y","Hidden":"N","Memory":"GETITDYNAMICALLY2","Cores":"GETITDYNAMICALLY3","Version":"GETITDYNAMICALLY4","Suite":"NA","SuiteVersion":"NA","OpenSource":"Y","IconUrl":"GETITDYNAMICALLY7","DownloadUrl":"https://hub.docker.com/r/GETITDYNAMICALLY5/tags","Identifier":"phpMyAdmin","Properties":[],"AppId":GETITDYNAMICALLY6}'
CLUSTER_APPS_OTHER_DETAILS["CHITRAGUPTA5"]='{"Name":"GETITDYNAMICALLY1","DisplayName":"Prometheus","CoreStack":"Y","Deployable":"Y","Configurable":"Y","Hidden":"N","Memory":"GETITDYNAMICALLY2","Cores":"GETITDYNAMICALLY3","Version":"GETITDYNAMICALLY4","Suite":"NA","SuiteVersion":"NA","OpenSource":"Y","IconUrl":"GETITDYNAMICALLY7","DownloadUrl":"https://hub.docker.com/r/GETITDYNAMICALLY5/tags","Identifier":"Prometheus","Properties":[],"AppId":GETITDYNAMICALLY6}'
CLUSTER_APPS_OTHER_DETAILS["CHITRAGUPTA6"]='{"Name":"GETITDYNAMICALLY1","DisplayName":"CAdvisor","CoreStack":"Y","Deployable":"Y","Configurable":"N","Hidden":"Y","Memory":"GETITDYNAMICALLY2","Cores":"GETITDYNAMICALLY3","Version":"GETITDYNAMICALLY4","Suite":"NA","SuiteVersion":"NA","OpenSource":"Y","IconUrl":"GETITDYNAMICALLY7","DownloadUrl":"https://hub.docker.com/r/GETITDYNAMICALLY5/tags","Identifier":"CAdvisor","Properties":[],"AppId":GETITDYNAMICALLY6}'
CLUSTER_APPS_OTHER_DETAILS["CHITRAGUPTA7"]='{"Name":"GETITDYNAMICALLY1","DisplayName":"Grafana","CoreStack":"Y","Deployable":"Y","Configurable":"Y","Hidden":"N","Memory":"GETITDYNAMICALLY2","Cores":"GETITDYNAMICALLY3","Version":"GETITDYNAMICALLY4","Suite":"NA","SuiteVersion":"NA","OpenSource":"Y","IconUrl":"GETITDYNAMICALLY7","DownloadUrl":"https://hub.docker.com/r/GETITDYNAMICALLY5/tags","Identifier":"Grafana","Properties":[],"AppId":GETITDYNAMICALLY6}'
CLUSTER_APPS_OTHER_DETAILS["CHITRAGUPTA8"]='{"Name":"GETITDYNAMICALLY1","DisplayName":"NodeExporter","CoreStack":"Y","Deployable":"Y","Configurable":"N","Hidden":"Y","Memory":"GETITDYNAMICALLY2","Cores":"GETITDYNAMICALLY3","Version":"GETITDYNAMICALLY4","Suite":"NA","SuiteVersion":"NA","OpenSource":"Y","IconUrl":"GETITDYNAMICALLY7","DownloadUrl":"https://hub.docker.com/r/GETITDYNAMICALLY5/tags","Identifier":"NodeExporter","Properties":[],"AppId":GETITDYNAMICALLY6}'
CLUSTER_APPS_OTHER_DETAILS["CHITRAGUPTA9"]='{"Name":"GETITDYNAMICALLY1","DisplayName":"OpenLDAP","CoreStack":"Y","Deployable":"Y","Configurable":"Y","Hidden":"N","Memory":"GETITDYNAMICALLY2","Cores":"GETITDYNAMICALLY3","Version":"GETITDYNAMICALLY4","Suite":"NA","SuiteVersion":"NA","OpenSource":"Y","IconUrl":"GETITDYNAMICALLY7","DownloadUrl":"https://hub.docker.com/r/GETITDYNAMICALLY5/tags","Identifier":"OpenLDAP","Properties":[],"AppId":GETITDYNAMICALLY6}'
CLUSTER_APPS_OTHER_DETAILS["CHITRAGUPTA10"]='{"Name":"GETITDYNAMICALLY1","DisplayName":"phpLDAPadmin","CoreStack":"Y","Deployable":"Y","Configurable":"Y","Hidden":"N","Memory":"GETITDYNAMICALLY2","Cores":"GETITDYNAMICALLY3","Version":"GETITDYNAMICALLY4","Suite":"NA","SuiteVersion":"NA","OpenSource":"Y","IconUrl":"GETITDYNAMICALLY7","DownloadUrl":"https://hub.docker.com/r/GETITDYNAMICALLY5/tags","Identifier":"phpLDAPadmin","Properties":[],"AppId":GETITDYNAMICALLY6}'
CLUSTER_APPS_OTHER_DETAILS["CHITRAGUPTA11"]='{"Name":"GETITDYNAMICALLY1","DisplayName":"Kerberos","CoreStack":"Y","Deployable":"Y","Configurable":"Y","Hidden":"N","Memory":"GETITDYNAMICALLY2","Cores":"GETITDYNAMICALLY3","Version":"GETITDYNAMICALLY4","Suite":"NA","SuiteVersion":"NA","OpenSource":"Y","IconUrl":"GETITDYNAMICALLY7","DownloadUrl":"https://hub.docker.com/r/GETITDYNAMICALLY5/tags","Identifier":"Kerberos","Properties":[],"AppId":GETITDYNAMICALLY6}'
CLUSTER_APPS_OTHER_DETAILS["EFK1"]='{"Name":"GETITDYNAMICALLY1","DisplayName":"Elastic Search","CoreStack":"Y","Deployable":"Y","Configurable":"Y","Hidden":"N","Memory":"GETITDYNAMICALLY2","Cores":"GETITDYNAMICALLY3","Version":"GETITDYNAMICALLY4","Suite":"NA","SuiteVersion":"NA","OpenSource":"Y","IconUrl":"GETITDYNAMICALLY7","DownloadUrl":"https://hub.docker.com/r/GETITDYNAMICALLY5/tags","Identifier":"ElasticSearch","Properties":[],"AppId":GETITDYNAMICALLY6}'
CLUSTER_APPS_OTHER_DETAILS["EFK2"]='{"Name":"GETITDYNAMICALLY1","DisplayName":"Kibana","CoreStack":"Y","Deployable":"Y","Configurable":"Y","Hidden":"N","Memory":"GETITDYNAMICALLY2","Cores":"GETITDYNAMICALLY3","Version":"GETITDYNAMICALLY4","Suite":"NA","SuiteVersion":"NA","OpenSource":"Y","IconUrl":"GETITDYNAMICALLY7","DownloadUrl":"https://hub.docker.com/r/GETITDYNAMICALLY5/tags","Identifier":"Kibana","Properties":[],"AppId":GETITDYNAMICALLY6}'
CLUSTER_APPS_OTHER_DETAILS["EFK3"]='{"Name":"GETITDYNAMICALLY1","DisplayName":"Filebeat","CoreStack":"Y","Deployable":"Y","Configurable":"N","Hidden":"Y","Memory":"GETITDYNAMICALLY2","Cores":"GETITDYNAMICALLY3","Version":"GETITDYNAMICALLY4","Suite":"NA","SuiteVersion":"NA","OpenSource":"Y","IconUrl":"GETITDYNAMICALLY7","DownloadUrl":"https://hub.docker.com/r/GETITDYNAMICALLY5/tags","Identifier":"Filebeat","Properties":[],"AppId":GETITDYNAMICALLY6}'

declare -A CLUSTER_APPS_MAPPING
CLUSTER_APPS_MAPPING["BRAHMA"]="portainer/portainer-ce"
CLUSTER_APPS_MAPPING["VISHVAKARMA"]="portainer/agent"
CLUSTER_APPS_MAPPING["INDRA"]="haproxy"
CLUSTER_APPS_MAPPING["BUCKET"]="minio/minio"
CLUSTER_APPS_MAPPING["CLOUDCOMMANDER"]="coderaiser/cloudcmd"
CLUSTER_APPS_MAPPING["PVTCLD"]="minus1by12/sanatan"
CLUSTER_APPS_MAPPING["BUCKETCLIENT"]="mc"
CLUSTER_APPS_MAPPING["CHITRAGUPTA1"]="guacamole/guacamole"
CLUSTER_APPS_MAPPING["CHITRAGUPTA2"]="guacamole/guacd"
CLUSTER_APPS_MAPPING["CHITRAGUPTA3"]="mysql"
CLUSTER_APPS_MAPPING["CHITRAGUPTA4"]="phpmyadmin"
CLUSTER_APPS_MAPPING["CHITRAGUPTA5"]="prom/prometheus"
CLUSTER_APPS_MAPPING["CHITRAGUPTA6"]="minus1by12/sanatan"
CLUSTER_APPS_MAPPING["CHITRAGUPTA7"]="grafana/grafana"
CLUSTER_APPS_MAPPING["CHITRAGUPTA8"]="prom/node-exporter"
CLUSTER_APPS_MAPPING["CHITRAGUPTA9"]="minus1by12/sanatan"
CLUSTER_APPS_MAPPING["CHITRAGUPTA10"]="minus1by12/sanatan"
CLUSTER_APPS_MAPPING["CHITRAGUPTA11"]="minus1by12/sanatan"
CLUSTER_APPS_MAPPING["EFK1"]="docker.elastic.co/elasticsearch/elasticsearch"
CLUSTER_APPS_MAPPING["EFK2"]="docker.elastic.co/kibana/kibana"
CLUSTER_APPS_MAPPING["EFK3"]="docker.elastic.co/beats/filebeat"

declare -A CLUSTERAPPSMAPPING
CLUSTERAPPSMAPPING["BRAHMA"]="lts"
CLUSTERAPPSMAPPING["VISHVAKARMA"]="lts"
CLUSTERAPPSMAPPING["INDRA"]="3.0.2"
CLUSTERAPPSMAPPING["BUCKET"]="latest"
CLUSTERAPPSMAPPING["BUCKETCLIENT"]="RELEASE.2024-07-26T13-08-44Z"
CLUSTERAPPSMAPPING["CLOUDCOMMANDER"]="17.4.1-alpine"
CLUSTERAPPSMAPPING["PVTCLD"]="pvtcld-$THECURRENTVERSIONOFSANATANIMPL"
CLUSTERAPPSMAPPING["CHITRAGUPTA1"]="1.5.5"
CLUSTERAPPSMAPPING["CHITRAGUPTA2"]="1.5.5"
CLUSTERAPPSMAPPING["CHITRAGUPTA3"]="9.0.1"
CLUSTERAPPSMAPPING["CHITRAGUPTA4"]="5.2.1"
CLUSTERAPPSMAPPING["CHITRAGUPTA5"]="v2.53.1"
CLUSTERAPPSMAPPING["CHITRAGUPTA6"]="cadvisor-$THECURRENTVERSIONOFSANATANIMPL"
CLUSTERAPPSMAPPING["CHITRAGUPTA7"]="11.1.1"
CLUSTERAPPSMAPPING["CHITRAGUPTA8"]="v1.8.2"
CLUSTERAPPSMAPPING["CHITRAGUPTA9"]="openldap-$THECURRENTVERSIONOFSANATANIMPL"
CLUSTERAPPSMAPPING["CHITRAGUPTA10"]="phpldapadmin-$THECURRENTVERSIONOFSANATANIMPL"
CLUSTERAPPSMAPPING["CHITRAGUPTA11"]="kerberos-$THECURRENTVERSIONOFSANATANIMPL"
CLUSTERAPPSMAPPING["EFK1"]="8.15.0"
CLUSTERAPPSMAPPING["EFK2"]="8.15.0"
CLUSTERAPPSMAPPING["EFK3"]="8.15.0"

declare -A CLUSTER_MEMORYCORES_MAPPING
CLUSTER_MEMORYCORES_MAPPING["BRAHMA"]="2048:2"
CLUSTER_MEMORYCORES_MAPPING["VISHVAKARMA"]="512:0.5"
CLUSTER_MEMORYCORES_MAPPING["INDRA"]="2048:2"
CLUSTER_MEMORYCORES_MAPPING["BUCKET"]="1024:1"
CLUSTER_MEMORYCORES_MAPPING["BUCKETCLIENT"]="1024:1"
CLUSTER_MEMORYCORES_MAPPING["CLOUDCOMMANDER"]="512:0.5"
CLUSTER_MEMORYCORES_MAPPING["PVTCLD"]="2048:2"
CLUSTER_MEMORYCORES_MAPPING["CHITRAGUPTA1"]="1024:1"
CLUSTER_MEMORYCORES_MAPPING["CHITRAGUPTA2"]="1024:1"
CLUSTER_MEMORYCORES_MAPPING["CHITRAGUPTA3"]="2048:2"
CLUSTER_MEMORYCORES_MAPPING["CHITRAGUPTA4"]="512:0.5"
CLUSTER_MEMORYCORES_MAPPING["CHITRAGUPTA5"]="2048:2"
CLUSTER_MEMORYCORES_MAPPING["CHITRAGUPTA6"]="1024:1"
CLUSTER_MEMORYCORES_MAPPING["CHITRAGUPTA7"]="1024:1"
CLUSTER_MEMORYCORES_MAPPING["CHITRAGUPTA8"]="512:0.5"
CLUSTER_MEMORYCORES_MAPPING["CHITRAGUPTA9"]="1024:1"
CLUSTER_MEMORYCORES_MAPPING["CHITRAGUPTA10"]="1024:1"
CLUSTER_MEMORYCORES_MAPPING["CHITRAGUPTA11"]="1024:1"
CLUSTER_MEMORYCORES_MAPPING["EFK1"]="4096:2"
CLUSTER_MEMORYCORES_MAPPING["EFK2"]="2048:1"
CLUSTER_MEMORYCORES_MAPPING["EFK3"]="512:0.5"

# Function to generate MySQL
GetAppVersionCompleteSQL() {
	# Define MySQL credentials
	DB_HOST="localhost"
	DB_USER="your_username"
	DB_PASS="your_password"
	DB_NAME="your_database"

	# JSON data (you can also read this from a file)
	JSON_DATA=$(<apps.json)

	# Loop through each app in the JSON data and insert into MySQL
	echo "$JSON_DATA" | jq -c '.Apps[]' | while IFS= read -r app; do
	    AppId=$(echo "$app" | jq -r '.AppId')
	    Name=$(echo "$app" | jq -r '.Name')
	    DisplayName=$(echo "$app" | jq -r '.DisplayName')
	    CoreStack=$(echo "$app" | jq -r '.CoreStack')
	    Deployable=$(echo "$app" | jq -r '.Deployable')
	    Configurable=$(echo "$app" | jq -r '.Configurable')
	    Hidden=$(echo "$app" | jq -r '.Hidden')
	    Memory=$(echo "$app" | jq -r '.Memory')
	    Cores=$(echo "$app" | jq -r '.Cores')
	    Version=$(echo "$app" | jq -r '.Version')
	    Suite=$(echo "$app" | jq -r '.Suite')
	    SuiteVersion=$(echo "$app" | jq -r '.SuiteVersion')
	    OpenSource=$(echo "$app" | jq -r '.OpenSource')
	    IconUrl=$(echo "$app" | jq -r '.IconUrl')
	    DownloadUrl=$(echo "$app" | jq -r '.DownloadUrl')
	    Identifier=$(echo "$app" | jq -r '.Identifier')
	    Properties=$(echo "$app" | jq -c '.Properties')

	    # MySQL Insert Command
	    mysql -h "$DB_HOST" -u "$DB_USER" -p"$DB_PASS" "$DB_NAME" -e "
		INSERT INTO Apps (AppId, Name, DisplayName, CoreStack, Deployable, Configurable, Hidden, Memory, Cores, Version, Suite, SuiteVersion, OpenSource, IconUrl, DownloadUrl, Identifier, Properties)
		VALUES ($AppId, '$Name', '$DisplayName', '$CoreStack', '$Deployable', '$Configurable', '$Hidden', $Memory, $Cores, '$Version', '$Suite', '$SuiteVersion', '$OpenSource', '$IconUrl', '$DownloadUrl', '$Identifier', '$Properties')
		ON DUPLICATE KEY UPDATE 
		    Name='$Name', 
		    DisplayName='$DisplayName', 
		    CoreStack='$CoreStack', 
		    Deployable='$Deployable', 
		    Configurable='$Configurable', 
		    Hidden='$Hidden', 
		    Memory=$Memory, 
		    Cores=$Cores, 
		    Version='$Version', 
		    Suite='$Suite', 
		    SuiteVersion='$SuiteVersion', 
		    OpenSource='$OpenSource', 
		    IconUrl='$IconUrl', 
		    DownloadUrl='$DownloadUrl', 
		    Identifier='$Identifier', 
		    Properties='$Properties';
	    "
	done
}

# Function to generate final JSON
GetAppVersionCompleteJSON() {
  # File path
  local json_file="$1.temp"
  local temp_file="$1"
  
  # Delete the existing file if it exists
  if [ -f "$json_file" ]; then
    rm -f "$json_file"
  fi

  # Create a new file
  touch "$json_file"

  # Start the JSON array
  echo "{\"Apps\": [" > "$json_file"

  # Loop through the total number of apps
  for ((i=1; i<=CLUSTER_APPS_TOTAL_NUMBER; i++)); do
    app_name=${CLUSTER_APPS_NUMBERING[$i]}  # Get app Name

    # Get respective details from other mappings
    memory_and_cores=${CLUSTER_MEMORYCORES_MAPPING[$app_name]}
    memory=$(echo $memory_and_cores | cut -d':' -f1)  # Extract memory
    cores=$(echo $memory_and_cores | cut -d':' -f2)   # Extract cores

    mapping=${CLUSTER_APPS_MAPPING[$app_name]}
    app_version=${CLUSTERAPPSMAPPING[$app_name]}

    full_version="${mapping}:${app_version}"  # Compose full Version

    icon_url="${app_name}.png"  # Set the icon URL

    # Get the app details and replace the placeholders dynamically
    app_details=${CLUSTER_APPS_OTHER_DETAILS[$app_name]}
    app_details=${app_details//GETITDYNAMICALLY1/$app_name}
    app_details=${app_details//GETITDYNAMICALLY2/$memory}
    app_details=${app_details//GETITDYNAMICALLY3/$cores}
    app_details=${app_details//GETITDYNAMICALLY4/$full_version}
    app_details=${app_details//GETITDYNAMICALLY5/$mapping}
    app_details=${app_details//GETITDYNAMICALLY6/$i}
    app_details=${app_details//GETITDYNAMICALLY7/$icon_url}
    app_details=${app_details//GETITDYNAMICALLY8/$app_name}

    # Append the details to the JSON file
    echo "$app_details," >> "$json_file"
  done

  # Remove the last comma and close the JSON array
  sed -i '$ s/,$//' "$json_file"
  echo "]}" >> "$json_file"
  
  jq '.' "$json_file" > "$temp_file"
  rm -f "$json_file"  
}

#/opt/Matsya/Scripts/MAYADHI.sh 'VAMANA' 'GetAppVersionCompleteJSON' '/opt/Matsya/tmp/Apps.json'
#/opt/Matsya/Scripts/MAYADHI.sh 'VAMANA' 'GetAppVersionCompleteSQL' '/opt/Matsya/tmp/Apps.sql'

