#!/bin/bash

if [ "$#" -ne 3 ]; then
    echo "
=====================================  
Params -: 
[1] (I)nclude / (E)xclude Coordinator 
[2] Password For User => vagrant 
[3] Full Path Of The Required File
=====================================
    "
    exit
fi

BASE="THEBASELOCATION"
COORDINATOR="THECOORDINATOR"
CLUSTERNAME="THECLUSTERNAME"
RANDOMSSHPORT="THERANDOMSSHPORT"

for Config in $BASE/VagVBox/$CLUSTERNAME/Configs/*; do
    if [ -d "$Config" ]; then
    	Config=${Config//$BASE/}
    	Config=${Config//VagVBox/}
    	Config=${Config//$CLUSTERNAME/}
    	Config=${Config//Configs/}
    	Config=${Config//matsya-vagvbox-sa/}
    	Config=${Config//\//}
    	Config=${Config//-/.}
    	Config=${Config//../}
    	CHOICE=$1
    	if [ $CHOICE == "E" ] || [ $CHOICE == "e" ] ; then
		if [ $Config == "$COORDINATOR" ] || [ $Config == "$COORDINATOR" ] ; then
			Config="Coordinator"
		fi
	fi    	
	if [ $Config == "Coordinator" ] || [ $Config == "Coordinator" ] ; then
		echo ""
	else
		echo "----------------"
		echo "$Config"
		echo "----------------"
		echo 'Copy Started...'
		echo '~~~~~~~~~~~~~~~~'
		sudo sshpass -p $2 scp -P $RANDOMSSHPORT -o "StrictHostKeyChecking=no" $3 vagrant@$Config:/home/vagrant
		echo 'Copy Complete...'
		echo '~~~~~~~~~~~~~~~~'		
		echo ''
	fi    	
    fi
done


