#!/bin/bash

E2ERESPONSE=$(curl 'https://api.e2enetworks.com/myaccount/api/v1/nodes/?apikey=E2ETHEAPIKEY&project_id=E2ETHEPROJECTCHOICE&location=E2ETHEVMLOCATION' \
-H 'Accept: application/json, text/plain, */*' \
-H 'Accept-Language: en-gb' \
-H 'Authorization: Bearer E2ETHEAUTHTOKEN' \
-H 'Content-Type: application/json' \
-H 'Origin: https://myaccount.e2enetworks.com' \
-H 'Pragma: no-cache' \
-H 'Referer: https://myaccount.e2enetworks.com/' \
-H 'x-api-key: E2ETHEAPIKEY' \
--data-raw '{
  "label": "Default",
  "name": "E2ETHENAMEOFINSTANCE",
  "region": "E2ETHEREGION",
  "plan": "E2ETHEPLAN",
  "image": "E2ETHEDISTRO",
  "ssh_keys": [
    "E2ETHESSHKEYS"
  ],
  "start_scripts": [],
  "backups": false,
  "enable_bitninja": false,
  "disable_password": true,
  "is_saved_image": false,
  "saved_image_template_id": null,
  "reserve_ip": "",
  "reserve_ip_pool": "",
  "is_ipv6_availed": false,
  "vpc_id": "",
  "default_public_ip": false,
  "ngc_container_id": null,
  "is_encryption_required": false
}' \
--compressed)

echo $E2ERESPONSE > E2ETHEPLACETOSAVERESPONSE
