#!/bin/bash

E2ERESPONSE=$(curl --location --request PUT 'https://api.e2enetworks.com/myaccount/api/v1/nodes/E2ETHENEWNODEID/actions/?apikey=E2ETHEAPIKEY&project_id=E2ETHEPROJECTCHOICE&location=E2ETHEVMLOCATION' \
 --header 'Accept: application/json, text/plain, */*' \
 --header 'Authorization: Bearer E2ETHEAUTHTOKEN' \
 --header 'Content-Type: application/json' \
 --header 'x-api-key: E2ETHEAPIKEY' \
 --data '{
          "name": "E2ETHENEWNODENAME",
          "type":"rename"
          }')
