#!/bin/bash

set -e

RED='\033[0;31m'
NC='\033[0m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
BLUE='\033[0;34m'
LBLUE='\033[1;34m'
DGRAY='\033[1;35m'
PURPLE='\033[0;35m'
RGRAY='\033[1;30m'
BOLD=$(tput bold)
NORM=$(tput sgr0)
ORANGE='\033[1;33m'

CURRENTUSER=$(whoami)

BASE="/opt/Matsya"
sudo mkdir -p $BASE
sudo mkdir -p $BASE/tmp
sudo mkdir -p $BASE/Scripts
sudo mkdir -p $BASE/Secrets
sudo mkdir -p $BASE/Resources
sudo mkdir -p $BASE/Output

USERINTERACTION="YES"
USERVALS=""

DIFF=$((600000-500000+1))
R=$(($(($RANDOM%$DIFF))+500000))
RANDOMFILENAME=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 15 | head -n 1)
RANDOMKEY=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 15 | head -n 1)
RKEY1=${RANDOMKEY:0:7}
RKEY2=${RANDOMKEY:7:8}
RANDOMKEY="$RKEY1$R$RKEY2"

if [ "$#" -ne 1 ]; then
	USERVALS=""
else
	USERVALS=$1
	USERINTERACTION="NO"
	IFS='├' read -r -a USERLISTVALS <<< $USERVALS
	SECRETSTHEFILE="${USERLISTVALS[0]}"
	THECHOICE="${USERLISTVALS[1]}"
	THE2CHOICE="${USERLISTVALS[2]}"	
	THENORMALPATH="${USERLISTVALS[3]}"
	SECRETTHEKEY="${USERLISTVALS[4]}"				
fi

if [ "$USERINTERACTION" == "YES" ] || [ "$USERINTERACTION" == "yes" ] ; then
	clear

	echo -e "${ORANGE}==============================================================================${NC}"
	echo -e "${BLUE}${BOLD}\x1b[4mM${NORM}${NC}ultifaceted deploy${BLUE}${BOLD}\x1b[4mA${NORM}${NC}gnostic ${BLUE}${BOLD}\x1b[4mT${NORM}${NC}imesaving ${BLUE}${BOLD}\x1b[4mS${NORM}${NC}calable anal${BLUE}${BOLD}\x1b[4mY${NORM}${NC}tics ${BLUE}${BOLD}\x1b[4mA${NORM}${NC}malgamated ${BOLD}\x1b[30;44mPLATFORM\x1b[m${NORM}"
	echo -e "${GREEN}==============================================================================${NC}"
	echo ''
	echo -e "\x1b[3m\x1b[4mSecret File Decryption\x1b[m"
	echo ''
fi

if [ "$USERINTERACTION" == "YES" ] || [ "$USERINTERACTION" == "yes" ] ; then
	read -p "Secrets File Location 			> " -e -i "" SECRETSTHEFILE
	echo ""
	read -p "Choice Decrypt(1) / Execute(2) 		> " -e -i "2" THECHOICE
	echo ""
	read -p "Choice Single(1) / Multi(2) 		> " -e -i "1" THE2CHOICE
	echo ""	
	if [ "$THECHOICE" == "1" ] ; then
		read -p "Normal File Path 	> " -e -i "" THENORMALPATH
		echo ""
	fi
	read -s -p "Secrets File Key 			> " -e -i "" SECRETTHEKEY
	echo ''	
	echo ''
fi

for SECRETSTHESINGLEFILE in $SECRETSTHEFILE
do
	if [ -f "$SECRETSTHESINGLEFILE" ]
	then
		ITER=${SECRETTHEKEY:7:6}
		RANDOMSECFILENAME=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 15 | head -n 1)
		sudo cp $SECRETSTHESINGLEFILE $BASE/tmp/$RANDOMSECFILENAME
		sudo chown $CURRENTUSER:$CURRENTUSER $BASE/tmp/$RANDOMSECFILENAME
		sudo chmod u=r,g=,o= $BASE/tmp/$RANDOMSECFILENAME
		REALSECRETSFILENAME=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 15 | head -n 1)
		openssl enc -a -d -aes-256-cbc -pbkdf2 -iter $ITER -k $SECRETTHEKEY -in $BASE/tmp/$RANDOMSECFILENAME -out $BASE/tmp/$REALSECRETSFILENAME
		sudo chown $CURRENTUSER:$CURRENTUSER $BASE/tmp/$REALSECRETSFILENAME
		sudo chmod u=r,g=,o= $BASE/tmp/$REALSECRETSFILENAME

		if [ "$THECHOICE" == "2" ] ; then
			sudo chmod u=rx,g=rx,o=rx $BASE/tmp/$REALSECRETSFILENAME
			sudo $BASE/tmp/$REALSECRETSFILENAME
		else
			if [ "$THE2CHOICE" == "1" ] ; then
				sudo mv $BASE/tmp/$REALSECRETSFILENAME $THENORMALPATH
			else
				sudo mv $BASE/tmp/$REALSECRETSFILENAME $THENORMALPATH/$REALSECRETSFILENAME
			fi
		fi
			
		sudo rm -rf $BASE/tmp/$REALSECRETSFILENAME				
		sudo rm -rf $BASE/tmp/$RANDOMSECFILENAME
		sudo rm -rf /root/.bash_history
		sudo rm -rf /home/$CURRENTUSER/.bash_history
	fi
done

